# Generated by Django 3.2.23 on 2024-08-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
