# Generated by Django 3.2.23 on 2024-10-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20240921_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='details',
            field=models.TextField(default='Blog_post'),
        ),
    ]
