# Generated by Django 3.2.23 on 2024-09-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20240920_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_time',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
