# Generated by Django 3.2.23 on 2024-10-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20241001_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='details',
            field=models.TextField(default=None, max_length=5500),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
